                        #String in Python
#Single & Double String:
name="Hello"
name1='Word'

print(name)
print(name1)


stetment="The language 'PYTHON' is named after Monty Python."
print(stetment)

statement2= "Hello !" Iam Jaspreet ."Hows your Mother??"
print(statement2)

statement="Hello!\" Iam Jaspreet\". How\'s your mother??"
print(statement)

statement2="The language \'PYTHON\' is  named after Monty Python"
print(statement2)

statement3="Hello!\" Iam \'Rafiul\'\". And Your??"
print(statement3)

statement4="Iam \'RFIUL\'.\" Iam a student in \'KURIGRAM POLYTECHNIC INSTITUTE\'.\"Dipertment of \'COMPUTER SCIENCE & TECHNOLOGY\'"
print(statement4)





#Multi-Line String:

statement=""" Hello! 
... This is Juspreet.
... How are You??"""
print(statement)


statement_1=""" How are you??
...I am fine.
...What about you??"""
print(statement_1)

statement_2= """ Hi!
... Iam Rafi!!
...And You??"""
print(statement_2)


statement_3="""Hello!!! Alex, How are you??
...Alex says 'Iam fine'.
...Alex asked 'And You??'"""
print(statement_3)


                    #Accessing String Characters in Python
#Accessing Individual Characcters:                    
statement= 'HELLO'
print(statement[0])  
print(statement[1])     
print(statement[2])  
print(statement[3])
print(statement[4])    



#Accessing Individual Characters from the Last:
statement= 'HELLO'
print(statement[-1])
print(statement[-2])
print(statement[-3])
print(statement[-4])
print(statement[-5])




#Accessing the Substring of a String:
statement= 'HELLO'
print(statement[1:4])
print(statement[:5])
print(statement[2:6])


statement='HELLO'
print(statement[-4:-1])

statement='RAFIUL'
print(statement[-6:-2])
